/**
 * Public surface of `@aisecretary/design-tokens`.
 *
 * Consumers import either:
 *   - `@aisecretary/design-tokens/build/tokens.css`        (web global CSS)
 *   - `@aisecretary/design-tokens/build/tokens.tailwind.js` (Tailwind theme extension)
 *   - `@aisecretary/design-tokens/build/tokens.native`     (RN typed object)
 *
 * From the package root we only re-export TypeScript helpers — runtime
 * artifacts live in `build/` and are gitignored / generated by SD.
 */

export type { ContrastFailure, ContrastPair, ContrastReport } from './checks/contrast.js';
export {
  contrastRatio,
  findFailures,
  parseHex,
  relativeLuminance,
  runContrastCheck,
} from './checks/contrast.js';
