/**
 * TanStack Router setup — Story 1.6.
 *
 * The route tree is auto-generated by the `TanStackRouterVite` plugin
 * (configured in `vite.config.ts`) from files in `src/routes/`. The
 * generated tree (`routeTree.gen.ts`) is committed so `pnpm typecheck`
 * works in fresh clones without first running `vite dev`.
 *
 * The `Register` augmentation below tells TanStack about our typed
 * router instance so `<Link to="..." />` and `useNavigate({ to: ... })`
 * autocomplete + type-check the path strings.
 */

import { createRouter } from '@tanstack/react-router';
import { routeTree } from './routeTree.gen';

export const router = createRouter({
  routeTree,
  defaultPreload: 'intent',
  defaultPreloadStaleTime: 0,
});

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}
