/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DataRightsRouteImport } from './routes/data-rights'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as R404RouteImport } from './routes/404'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ShareTokenHashRouteImport } from './routes/share.$tokenHash'
import { Route as LtiLaunchRouteImport } from './routes/lti.launch'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedRecordRouteImport } from './routes/_authenticated/record'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedActionsRouteImport } from './routes/_authenticated/actions'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security'
import { Route as AuthenticatedSettingsMembersRouteImport } from './routes/_authenticated/settings/members'
import { Route as AuthenticatedSettingsInboundSharesRouteImport } from './routes/_authenticated/settings/inbound-shares'
import { Route as AuthenticatedSettingsDsarQueueRouteImport } from './routes/_authenticated/settings/dsar-queue'
import { Route as AuthenticatedSettingsBillingRouteImport } from './routes/_authenticated/settings/billing'
import { Route as AuthenticatedSettingsAuditLogRouteImport } from './routes/_authenticated/settings/audit-log'
import { Route as AuthenticatedSettingsAdminRouteImport } from './routes/_authenticated/settings/admin'
import { Route as AuthenticatedMeetingsMeetingIdRouteImport } from './routes/_authenticated/meetings/$meetingId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRightsRoute = DataRightsRouteImport.update({
  id: '/data-rights',
  path: '/data-rights',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ShareTokenHashRoute = ShareTokenHashRouteImport.update({
  id: '/share/$tokenHash',
  path: '/share/$tokenHash',
  getParentRoute: () => rootRouteImport,
} as any)
const LtiLaunchRoute = LtiLaunchRouteImport.update({
  id: '/lti/launch',
  path: '/lti/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecordRoute = AuthenticatedRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActionsRoute = AuthenticatedActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsMembersRoute =
  AuthenticatedSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsInboundSharesRoute =
  AuthenticatedSettingsInboundSharesRouteImport.update({
    id: '/inbound-shares',
    path: '/inbound-shares',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsDsarQueueRoute =
  AuthenticatedSettingsDsarQueueRouteImport.update({
    id: '/dsar-queue',
    path: '/dsar-queue',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsBillingRoute =
  AuthenticatedSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAuditLogRoute =
  AuthenticatedSettingsAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAdminRoute =
  AuthenticatedSettingsAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedMeetingsMeetingIdRoute =
  AuthenticatedMeetingsMeetingIdRouteImport.update({
    id: '/meetings/$meetingId',
    path: '/meetings/$meetingId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/404': typeof R404Route
  '/': typeof AuthenticatedIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/data-rights': typeof DataRightsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/actions': typeof AuthenticatedActionsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/record': typeof AuthenticatedRecordRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/lti/launch': typeof LtiLaunchRoute
  '/share/$tokenHash': typeof ShareTokenHashRoute
  '/meetings/$meetingId': typeof AuthenticatedMeetingsMeetingIdRoute
  '/settings/admin': typeof AuthenticatedSettingsAdminRoute
  '/settings/audit-log': typeof AuthenticatedSettingsAuditLogRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/dsar-queue': typeof AuthenticatedSettingsDsarQueueRoute
  '/settings/inbound-shares': typeof AuthenticatedSettingsInboundSharesRoute
  '/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
}
export interface FileRoutesByTo {
  '/404': typeof R404Route
  '/accept-invite': typeof AcceptInviteRoute
  '/data-rights': typeof DataRightsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/actions': typeof AuthenticatedActionsRoute
  '/chat': typeof AuthenticatedChatRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/record': typeof AuthenticatedRecordRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/lti/launch': typeof LtiLaunchRoute
  '/share/$tokenHash': typeof ShareTokenHashRoute
  '/': typeof AuthenticatedIndexRoute
  '/meetings/$meetingId': typeof AuthenticatedMeetingsMeetingIdRoute
  '/settings/admin': typeof AuthenticatedSettingsAdminRoute
  '/settings/audit-log': typeof AuthenticatedSettingsAuditLogRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/dsar-queue': typeof AuthenticatedSettingsDsarQueueRoute
  '/settings/inbound-shares': typeof AuthenticatedSettingsInboundSharesRoute
  '/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/404': typeof R404Route
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/data-rights': typeof DataRightsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/actions': typeof AuthenticatedActionsRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/record': typeof AuthenticatedRecordRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/lti/launch': typeof LtiLaunchRoute
  '/share/$tokenHash': typeof ShareTokenHashRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/meetings/$meetingId': typeof AuthenticatedMeetingsMeetingIdRoute
  '/_authenticated/settings/admin': typeof AuthenticatedSettingsAdminRoute
  '/_authenticated/settings/audit-log': typeof AuthenticatedSettingsAuditLogRoute
  '/_authenticated/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/_authenticated/settings/dsar-queue': typeof AuthenticatedSettingsDsarQueueRoute
  '/_authenticated/settings/inbound-shares': typeof AuthenticatedSettingsInboundSharesRoute
  '/_authenticated/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/404'
    | '/'
    | '/accept-invite'
    | '/data-rights'
    | '/login'
    | '/signup'
    | '/actions'
    | '/chat'
    | '/inbox'
    | '/record'
    | '/search'
    | '/settings'
    | '/team'
    | '/lti/launch'
    | '/share/$tokenHash'
    | '/meetings/$meetingId'
    | '/settings/admin'
    | '/settings/audit-log'
    | '/settings/billing'
    | '/settings/dsar-queue'
    | '/settings/inbound-shares'
    | '/settings/members'
    | '/settings/security'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/404'
    | '/accept-invite'
    | '/data-rights'
    | '/login'
    | '/signup'
    | '/actions'
    | '/chat'
    | '/inbox'
    | '/record'
    | '/search'
    | '/settings'
    | '/team'
    | '/lti/launch'
    | '/share/$tokenHash'
    | '/'
    | '/meetings/$meetingId'
    | '/settings/admin'
    | '/settings/audit-log'
    | '/settings/billing'
    | '/settings/dsar-queue'
    | '/settings/inbound-shares'
    | '/settings/members'
    | '/settings/security'
  id:
    | '__root__'
    | '/404'
    | '/_authenticated'
    | '/accept-invite'
    | '/data-rights'
    | '/login'
    | '/signup'
    | '/_authenticated/actions'
    | '/_authenticated/chat'
    | '/_authenticated/inbox'
    | '/_authenticated/record'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/lti/launch'
    | '/share/$tokenHash'
    | '/_authenticated/'
    | '/_authenticated/meetings/$meetingId'
    | '/_authenticated/settings/admin'
    | '/_authenticated/settings/audit-log'
    | '/_authenticated/settings/billing'
    | '/_authenticated/settings/dsar-queue'
    | '/_authenticated/settings/inbound-shares'
    | '/_authenticated/settings/members'
    | '/_authenticated/settings/security'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R404Route: typeof R404Route
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  DataRightsRoute: typeof DataRightsRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  LtiLaunchRoute: typeof LtiLaunchRoute
  ShareTokenHashRoute: typeof ShareTokenHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-rights': {
      id: '/data-rights'
      path: '/data-rights'
      fullPath: '/data-rights'
      preLoaderRoute: typeof DataRightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/share/$tokenHash': {
      id: '/share/$tokenHash'
      path: '/share/$tokenHash'
      fullPath: '/share/$tokenHash'
      preLoaderRoute: typeof ShareTokenHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lti/launch': {
      id: '/lti/launch'
      path: '/lti/launch'
      fullPath: '/lti/launch'
      preLoaderRoute: typeof LtiLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/record': {
      id: '/_authenticated/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof AuthenticatedRecordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/actions': {
      id: '/_authenticated/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof AuthenticatedActionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/members': {
      id: '/_authenticated/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AuthenticatedSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/inbound-shares': {
      id: '/_authenticated/settings/inbound-shares'
      path: '/inbound-shares'
      fullPath: '/settings/inbound-shares'
      preLoaderRoute: typeof AuthenticatedSettingsInboundSharesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/dsar-queue': {
      id: '/_authenticated/settings/dsar-queue'
      path: '/dsar-queue'
      fullPath: '/settings/dsar-queue'
      preLoaderRoute: typeof AuthenticatedSettingsDsarQueueRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/billing': {
      id: '/_authenticated/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/audit-log': {
      id: '/_authenticated/settings/audit-log'
      path: '/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof AuthenticatedSettingsAuditLogRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/admin': {
      id: '/_authenticated/settings/admin'
      path: '/admin'
      fullPath: '/settings/admin'
      preLoaderRoute: typeof AuthenticatedSettingsAdminRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/meetings/$meetingId': {
      id: '/_authenticated/meetings/$meetingId'
      path: '/meetings/$meetingId'
      fullPath: '/meetings/$meetingId'
      preLoaderRoute: typeof AuthenticatedMeetingsMeetingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAdminRoute: typeof AuthenticatedSettingsAdminRoute
  AuthenticatedSettingsAuditLogRoute: typeof AuthenticatedSettingsAuditLogRoute
  AuthenticatedSettingsBillingRoute: typeof AuthenticatedSettingsBillingRoute
  AuthenticatedSettingsDsarQueueRoute: typeof AuthenticatedSettingsDsarQueueRoute
  AuthenticatedSettingsInboundSharesRoute: typeof AuthenticatedSettingsInboundSharesRoute
  AuthenticatedSettingsMembersRoute: typeof AuthenticatedSettingsMembersRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAdminRoute: AuthenticatedSettingsAdminRoute,
  AuthenticatedSettingsAuditLogRoute: AuthenticatedSettingsAuditLogRoute,
  AuthenticatedSettingsBillingRoute: AuthenticatedSettingsBillingRoute,
  AuthenticatedSettingsDsarQueueRoute: AuthenticatedSettingsDsarQueueRoute,
  AuthenticatedSettingsInboundSharesRoute:
    AuthenticatedSettingsInboundSharesRoute,
  AuthenticatedSettingsMembersRoute: AuthenticatedSettingsMembersRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedActionsRoute: typeof AuthenticatedActionsRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedRecordRoute: typeof AuthenticatedRecordRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMeetingsMeetingIdRoute: typeof AuthenticatedMeetingsMeetingIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActionsRoute: AuthenticatedActionsRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedRecordRoute: AuthenticatedRecordRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMeetingsMeetingIdRoute: AuthenticatedMeetingsMeetingIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  R404Route: R404Route,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  DataRightsRoute: DataRightsRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  LtiLaunchRoute: LtiLaunchRoute,
  ShareTokenHashRoute: ShareTokenHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
