/**
 * Typed runtime re-export of the React-Native token tree emitted by
 * `packages/design-tokens` (Track 1). Use this for any RN code path
 * that needs to read a token imperatively (Animated drivers, Reanimated
 * worklets, native module options) — NativeWind handles the className
 * path. See arch-addendums § Token taxonomy for the orthogonal-axis
 * shape of the emitted object.
 *
 * The build artifact is generated by Style Dictionary; the file below
 * re-exports the named `tokens` const. If Track 1 has not run
 * `pnpm --filter @aisecretary/design-tokens build`, this import will
 * fail until the artifact lands.
 */
export { tokens } from '@aisecretary/design-tokens/build/tokens.native';
