/**
 * Style Dictionary custom format: typed React Native object tree.
 *
 * Emits a `tokens.native.ts` file shaped like:
 *
 *   export const tokens = {
 *     color: { bg: '#0a0a0a', accent: '#818cf8', accentSoft: '#818cf840', ... },
 *     space: { 0: '0px', 1: '4px', ... },
 *     ...
 *   } as const;
 *   export type Tokens = typeof tokens;
 *
 * Mode overlays are emitted as a sibling `modes` namespace so the host
 * (apps/mobile) can spread them at runtime — never pre-baked.
 */

import { resolvePlatformValue } from './color-mix-fallback.js';

// biome-ignore lint/suspicious/noExplicitAny: SD dictionary shape is loosely typed across major versions.
type SdDictionary = any;
// biome-ignore lint/suspicious/noExplicitAny: same as above.
type SdToken = any;

interface FormatArgs {
  dictionary: SdDictionary;
  // biome-ignore lint/suspicious/noExplicitAny: SD passes platform/file/options here; we only read shallow keys.
  options?: any;
  // biome-ignore lint/suspicious/noExplicitAny: SD passes platform/file/options here; we only read shallow keys.
  file?: any;
}

function camelCase(input: string): string {
  return input.replace(/[-_](\w)/g, (_, ch: string) => ch.toUpperCase());
}

function setDeep(target: Record<string, unknown>, path: string[], value: unknown): void {
  let cursor: Record<string, unknown> = target;
  for (let i = 0; i < path.length - 1; i += 1) {
    const segment = path[i];
    if (segment === undefined) continue;
    const key = camelCase(segment);
    const existing = cursor[key];
    if (typeof existing !== 'object' || existing === null) {
      cursor[key] = {};
    }
    cursor = cursor[key] as Record<string, unknown>;
  }
  const last = path[path.length - 1];
  if (last !== undefined) {
    cursor[camelCase(last)] = value;
  }
}

function tokensToTree(tokens: SdToken[]): Record<string, unknown> {
  const tree: Record<string, unknown> = {};
  for (const token of tokens) {
    const path: string[] = Array.isArray(token.path) ? token.path : [];
    if (path[0] === '_mode') continue;
    const value = resolvePlatformValue(token, 'native');
    setDeep(tree, path, value);
  }
  return tree;
}

function stringifyTree(tree: Record<string, unknown>, indent = 2): string {
  // JSON.stringify with sorted keys for deterministic output.
  const json = JSON.stringify(tree, null, indent);
  // Quote-strip object keys that are valid identifiers; numeric keys stay quoted.
  return json.replace(/"([A-Za-z_$][\w$]*)":/g, '$1:');
}

export const reactNativeTypedFormat = {
  name: 'rn/typed-object-tree',
  format: ({ dictionary }: FormatArgs): string => {
    const allTokens: SdToken[] = dictionary?.allTokens ?? [];
    const tree = tokensToTree(allTokens);
    const body = stringifyTree(tree);
    return [
      '/* AUTO-GENERATED by @aisecretary/design-tokens — do not edit. */',
      '/* Source: packages/design-tokens/tokens/*.json (ADR-0002). */',
      '',
      `export const tokens = ${body} as const;`,
      '',
      'export type Tokens = typeof tokens;',
      '',
    ].join('\n');
  },
};

export { resolvePlatformValue };
